# app/services/salesforce_question_mapping.rb

module SalesforceQuestionMapping
  def self.salesforce_id_for(qualtrics_id)
    case qualtrics_id
    when "QID1" then "FirstName__c"
    when "QID2" then "LastName__c"
    when "QID21" then "MiddleName__c"
    when "QID108" then "PreferredFirstName__c"
    when "QID131" then "Suffix__c"
    when "QID5" then "Birthdate__c"
    when "QID6" then "GenderIdentity__c"
    when "QID6_5" then "GenderIdentity__c"
    when "QID22" then "PrefferedPronouns__c"
    when "QID22_4" then "PronounsOther__c"
    when "QID7" then "RaceEthnicityInput__c"
    when "QID7_9" then "RaceEthnicityOther__c"
    when "QID110" then "CurrentIncome__c"
    when "QID113" then "CurrentHouseholdYearlyIncome__c"
    when "QID137" then "NumberOfPeopleInHousehold__c"
    when "QID111" then "CurrentEmploymentStatus__c"
    when "QID135" then "JobTitle__c"
    when "QID136" then "Industry__c"
    when "QID12" then "AssistanceQualificationInput__c"
    when "QID12_6" then "AssistanceQualificationOther__c"
    when "QID9" then "YearsofWorkExperience__c"
    when "QID128" then "Email__c"
    when "QID52" then "Phone__c"
    when "QID23" then "MailingAddress__Street__s"
    when "QID24" then "MailingAddress__City__s"
    when "QID25" then "MailingAddress__State_s"
    when "QID26" then "MailingAddress__PostalCode__s"
    when "QID41" then "HighSchoolProgram__c"
    when "QID64" then "HighSchoolGraduationYear__c"
    when "QID40" then "HighSchoolName__c"
    when "QID130" then "HighSchoolNameUnlisted__c"
    when "QID129" then "HighestLevelofEducation__c"
    when "QID129_9" then "OtherHighestLevelofEducation__c"
    when "QID138" then "FirstGenerationCollegeStudent__c"
    when "QID56" then "DegreePursued1__c"
    when "QID73" then "DegreePursued2__c"
    when "QID83" then "DegreePursued3__c"
    when "QID93" then "DegreePursued4__c"
    when "QID56_6" then "DegreePursuedOther1__c"
    when "QID73_6" then "DegreePursuedOther2__c"
    when "QID83_6" then "DegreePursuedOther3__c"
    when "QID93_6" then "DegreePursuedOther4__c"
    when "QID116" then "DidYouGraduate1__c"
    when "QID78" then "DidYouGraduate2__c"
    when "QID88" then "DidYouGraduate3__c"
    when "QID98" then "DidYouGraduate4__c"
    when "QID60" then "GraduationMonthYear1__c"
    when "QID118" then "GraduationMonthYear2__c"
    when "QID120" then "GraduationMonthYear3__c"
    when "QID122" then "GraduationMonthYear4__c"
    when "QID58" then "MajorFieldOfStudy1__c"
    when "QID75" then "MajorFieldOfStudy2__c"
    when "QID85" then "MajorFieldOfStudy3__c"
    when "QID95" then "MajorFieldOfStudy4__c"
    when "QID66" then "Minor1__c"
    when "QID76" then "Minor2__c"
    when "QID86" then "Minor3__c"
    when "QID96" then "Minor4__c"
    when "QID57" then "ProgramPresence1__c"
    when "QID74" then "ProgramPresence2__c"
    when "QID84" then "ProgramPresence3__c"
    when "QID94" then "ProgramPresence4__c"
    when "QID54" then "SchoolName1__c"
    when "QID71" then "SchoolName2__c"
    when "QID81" then "SchoolName3__c"
    when "QID91" then "SchoolName4__c"
    when "QID104" then "SchoolName1Unlisted__c"
    when "QID102" then "SchoolName2Unlisted__c"
    when "QID105" then "SchoolName3Unlisted__c"
    when "QID107" then "SchoolName4Unlisted__c"
    when "QID59" then "StartDate1__c"
    when "QID77" then "StartDate2__c"
    when "QID87" then "StartDate3__c"
    when "QID97" then "StartDate4__c"
    when "QID117" then "WithdrawalDate1__c"
    when "QID119" then "WithdrawalDate2__c"
    when "QID121" then "WithdrawalDate3__c"
    when "QID123" then "WithdrawalDate4__c"
    when "QID125" then "PreviousCSExperienceInput__c"
    when "QID126" then "TimeWritingCode__c"
    when "QID127" then "LastTimeWroteCode__c"
    when "QID11" then "HowDidYouHearAboutTheProgramInput__c"
    when "QID11_10" then "OtherHowDidYouHearAboutProgram__c"
    when "QID11_5" then "ReferralName__c"
    when "QID11_16" then "CareerJobBoardName__c"
    when "QID11_15" then "CareerJobFairName__c"
    else
      nil
    end
  end
  def self.non_qid(header)
    case header
    when "ProgramID__c" then "ProgramID__c"
    when "EnrollmentStatus__c" then "EnrollmentStatus__c"
    when "recordedDate" then "ApplicationSubmissionDate__c"
    else
      nil
    end
  end
end
