default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: student_portal_mvp_development

test:
  <<: *default
  database: student_portal_mvp_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

cache:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

queue:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

cable:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
