default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: student_portal_mvp_development

test:
  <<: *default
  database: student_portal_mvp_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *primary_production
    database: student_portal_mvp_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: student_portal_mvp_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: student_portal_mvp_production_cable
    migrations_paths: db/cable_migrate
